{"name": "test_01_phone_login", "status": "broken", "statusDetails": {"message": "TypeError: 'init' object is not callable", "trace": "cls = <class 'test_00_login.TestLogin'>\n\n    @classmethod\n    def setup_class(cls):\n>       init().activate_app()\nE       TypeError: 'init' object is not callable\n\ntests/test_00_login.py:17: TypeError"}, "description": "登录账号", "start": 1656053218163, "stop": 1656053218163, "uuid": "355cb0f3-95a4-49d5-9586-2cab992233e9", "historyId": "6bbda9dd678259dc795c231e4fb7cb31", "testCaseId": "6dfb9c3a830cddc8a55a8b655c34a00a", "fullName": "tests.test_00_login.TestLogin#test_01_phone_login", "labels": [{"name": "feature", "value": "登录"}, {"name": "tag", "value": "jw"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_00_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "jikedeMacBook-Pro-4.local"}, {"name": "thread", "value": "27698-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_00_login"}]}