{"name": "test_02_logout", "status": "broken", "statusDetails": {"message": "TypeError: 'init' object is not callable", "trace": "cls = <class 'test_00_login.TestLogin'>\n\n    @classmethod\n    def setup_class(cls):\n>       init().activate_app()\nE       TypeError: 'init' object is not callable\n\ntests/test_00_login.py:17: TypeError"}, "description": "登出账号", "start": 1656053218166, "stop": 1656053218166, "uuid": "6422650d-607f-447a-8207-0c53a66fd86f", "historyId": "bcf2bab7dcad3af909f858d9d2b34851", "testCaseId": "3d01b057db4bc879581203a15b03603b", "fullName": "tests.test_00_login.TestLogin#test_02_logout", "labels": [{"name": "feature", "value": "登录"}, {"name": "tag", "value": "jw"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_00_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "jikedeMacBook-Pro-4.local"}, {"name": "thread", "value": "27698-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_00_login"}]}